config/routes.rb
Rails.application.routes.draw do
  root'pages#index'

  resources :sports
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/Sport.rb
class Sport < ApplicationRecord

end 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def about

  end 
end

app/controllers/sports_controller.rb
class SportsController < ApplicationController

 def index
 @sports = Sport.all
 end

 def new
@sports = Sport.new
 end 

 def create
@sports = Sport.new(add_params)
 if @sports.save
 	flash[:notice] = "Sports Created Sucessfully"
 	redirect_to @sports
 end 
end

def show
@sport = Sport.find(params[:id])
end

def edit
@sports = Sport.find(params[:id])
end

def update
	@sports = Sport.find(params[:id])
if @sports.update(add_params)
	flash[:notice] = "Updated Sucessfully"
	redirect_to @sports
else
	render 'edit'
end

end

def destroy
@sport = Sport.find(params[:id])
@sport.destroy
redirect_to sports_path

end

 private

  def add_params
 
  params.require(:sport).permit(:name,:no_players,:discription)

  end

 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_navbar.html.erb
 <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item active">
        
        <%=link_to "Home",root_path,class:"nav-link" %>
      </li>
      <li class="nav-item active">
        <%=link_to "Sports",sports_path,class:"nav-link" %>
      </li>

       <li class="nav-item active">
        <a class="nav-link" href="#">Ratings <span class="sr-only">(current)</span></a>
      </li>

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Sports
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <ul>
         <% Sport.all.each do |sport| %>
          
          <li><%= link_to "#{sport.name}", sport_path(sport),class:"dropdown-item" %></li>

          <% end %>
           <%= link_to "All Sports", sports_path,class:"dropdown-item"%>
        <hr>
          <%= link_to "New Sports", new_sport_path,class:"dropdown-item"%>
        </ul>
        </div>
      </li>


      
      
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SportsRating</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

   <%= render 'layouts/navbar'%>

    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<h1>Pages#index</h1>

<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
     
      <%= image_tag("football.jpg", :alt => "rss feed",class:"d-block w-100 image_rotator") %>
	      <div class="carousel-caption d-none d-md-block">
	       <h5>Cricket</h5>
	       <p>England,Australia</p>
		  </div>
    </div>
    <div class="carousel-item">
    	<div class="carousel-caption d-none d-md-block title">
	       <h5>Cricket</h5>
	       <p>England,Australia</p>
		  </div>
      <%= image_tag("cricket.jpg", :alt => "rss feed",class:"d-block w-100 image_rotator") %>
	      
    </div>
    <div class="carousel-item">
      <%= image_tag("football.jpg", :alt => "rss feed",class:"d-block w-100 image_rotator") %>
	      <div class="carousel-caption d-none d-md-block">
	       <h5>Cricket</h5>
	       <p>England,Australia</p>
		  </div>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>

app/views/sports/_form.html.erb
<div class ="container form_container">
<%= form_for(@sports, :html => {class: "form-horizontal", role: "form"}) do |f| %>
  <div class="form-group">

    <div class="control-label col-sm-2">

    <%= f.label :name %>

    </div>

    <div class="col-sm-8">

    <%= f.text_field :name, class: "form-control", placeholder: "Name Of Sports", autofocus: true %>

    </div>
</div>
  

   <div class="form-group">

      <div class="control-label col-sm-2">

      <%= f.label :Players %>

      </div>

      <div class="col-sm-8">

      <%= f.text_field :no_players, class: "form-control", placeholder: "Total Players", autofocus: true %>

      </div>
</div>

 <div class="form-group">

    <div class="control-label col-sm-2">

    <%= f.label :Discription %>

    </div>

    <div class="col-sm-8">

    <%= f.text_area :discription,rows:6, class: "form-control", placeholder: "Discription", autofocus: true %>

    </div>
</div>

<div class ="form-group">
    <div class="col-sm-8">
  <div class="input-group mb-3">
    <div class="input-group-prepend">
      <span class="input-group-text">Upload</span>
    </div>
    <div class="custom-file">
      <input type="file" class="custom-file-input" id="inputGroupFile01">
      <label class="custom-file-label" for="inputGroupFile01">Choose file</label>
    </div>
  </div>
  </div>
</div>
<div class ="form-group">
    <div class="col-sm-8">
      <div class="custom-control custom-checkbox">
        <input type="checkbox" class="custom-control-input" id="customCheck1">
        <label class="custom-control-label" for="customCheck1">Agree this Form</label>
      </div>
    </div>
</div>

<div class="form-group">

  <div class="col-sm-offset-2 col-sm-10">

  <%= f.submit(@sports.new_record? ? :"Create" : :"Update",class: 'btn btn-primary btn-lg')%>

  </div>

</div>


<% end %>
</div>

app/views/sports/edit.html.erb
<%= render 'form' %>

app/views/sports/index.html.erb
<div class="card-deck  container-list">
	<%@sports.each do |sport| %>
  <div class="card card text-white bg-warning">
    <%= image_tag("football.jpg", :alt => "rss feed",class:"card-img-top") %>
    <div class="card-body">
      <h5 class="card-title"><%=sport.name%></h5>
      <p class="card-text"><%=sport.no_players%></p>
      <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
      
      <%= link_to "View", sport_path(sport),class:"btn btn-success"%>
      <%= link_to "Vote", "",class:"btn btn-success"%>
    </div>

  </div>
  <% end %>
</div>

app/views/sports/new.html.erb
<%=render 'form' %>

app/views/sports/show.html.erb
<div class ="container container-list-show">

	<div class="row">
		<div class="col-sm-6">
			<div class="card text-white bg-warning" style="width: 18rem;">
			  <%= image_tag("football.jpg", :alt => "rss feed",class:"card-img-top") %>
			 <div class="card-body">

			      <h5 class="card-title">
			      	<span>SportName:<%=@sport.name%>
			      	</span></h5>
			      <span><p class="card-text">Total Players:<%=@sport.no_players%></p></span>
			      <span><p class="card-text">Discription:<%=@sport.discription%></p></span>
			      <hr>
			      <span><p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p></span>
			      <hr>
			      
			      <%= link_to "Edit", edit_sport_path(@sport),class:"btn btn-success"%>
			      <%= link_to "Delete", sport_path(@sport),method: :delete,
			      data: { confirm: "Are you sure you want to delete the Sport?"},class:"btn btn-success"%>
			    </div>
			</div>
		</div>
	</div>
</div>